# Generated by Django 2.0.1 on 2018-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181218_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(choices=[('18611223344', 'wangxin de phone'), ('13911223344', 'who de phone')], max_length=11, null=True, unique=True),
        ),
    ]
