# Generated by Django 2.0.1 on 2019-03-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(default=True, verbose_name='是否一级菜单'),
        ),
    ]
