# Generated by Django 2.0.1 on 2019-03-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='父类菜单的ID，如果ID为None，那么就是菜单，如果不为None那么就是按钮', null=True, on_delete=True, to='rbac.Permission', verbose_name='父类菜单ID'),
        ),
    ]
